### ISSUE TITLE
Separation between distances and collisions

### ISSUE THREAD

**Issue by nmansard** [humanoid-path-planner/hpp-model#32]
In hpp::model, two lists are kept for pairs of object that must be tested for collision, and those for which distances must be computed. Is it important to keep these two sets explicitly? Or can we have only one set, while either collisions or distances are computed by calling the respective method?

Is anybody using a model where the two lists InnerObjects(DISTANCE|COLLISION) are different (and resp. the two lists outerObjects(DISTANCE|COLLISION) are different)?

**Comment by florent-lamiraux** [comment]
I do not think that we actually use the distance list, @jmirabel may confirm.
It did that because in the past, I had an example where is was useful, but I do not think it is worth keeping this feature (unless it is used by someone).

**Comment by jmirabel** [comment]
I don't think it is used anywhere in C++ and don't see anything that cannot be done with one list only.

**Comment by nmansard** [comment]
Fair enought. Thanks for the answer. I am closing.
