### ISSUE TITLE
Access to collisionPairs

### ISSUE THREAD

**Issue by nmansard** [humanoid-path-planner/hpp-model#33]
In class Device, methods are implemented to add and remove collision pairs, and to access the list of collision pairs. Collision pairs are pairs of joints (or equivalently bodies). When a pair is added, all the inner objects of joint 1 are added as outer objects of joint 2. The information contained in the pairs is somehow duplicated in the inner/outer lists: we can remove some outer objects without removing the corresponding pair of joints. Device::CollisionPair may then be outdated without any trouble. 

Pinocchio does not maintain such a CollisionPairs structure. 

I believe that this structure of hpp::model is weakly used, if not at all. Should I try to mimic it in hpp-pinocchio? Or can we consider this function as deprecated?

**Comment by florent-lamiraux** [comment]
Collision pairs of a Device are accessed in the following file.
https://github.com/humanoid-path-planner/hpp-core/blob/master/src/collision-validation.cc:175

It is sometimes necessary to rebuild the pairs of objects that need to be checked for collision. For instance class CollisionValidation initializes pairs with the inner objects of joints that are potentially colliding. Then method filterCollisionPairs removes some pairs depending on information about relative joint motion provided
